version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /client
  static_dir: client
- url: /bower_components
  static_dir: bower_components
- url: /redirect/.*
  script: redirect.app
- url: /.*
  script: redirect.app
