application: chromez-app
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /redirect/.*
  script: redirect.app
- url: /
  upload: client/simple.html
  static_files: client/simple.html
- url: /bower_components/(.+\.(js|html))
  static_files: bower_components/\1
  upload: bower_components/.*
- url: /(.+\.(js|html))
  static_files: client/\1
  upload: client/.*
